name: Continuous Integration
on:
  pull_request:
  push:
    branches: [master]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: 'true'

      - name: Install Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0

      - name: Install dependencies
        run: npm install

  scan:
    needs: lint-and-test
    if: ${{ github.event_name == 'pull_request' && github.event.repository.private == false }}
    uses: circlefin/circle-public-github-workflows/.github/workflows/pr-scan.yaml@v1

  release-sbom:
    needs: lint-and-test
    if: github.event_name == 'push'
    uses: circlefin/circle-public-github-workflows/.github/workflows/attach-release-assets.yaml@v1